#!/bin/bash

file=$(find . -name "*.[ch]" -o -name "*.cpp")
for i in $file
do
    echo $i
    astyle --style=linux --convert-tabs --suffix=none --pad-oper --unpad-paren --pad-header --indent=spaces=4 --max-instatement-indent=120 $i
done
