/*
 * Header file used only in HWMC_ONLY mode
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */
// Module name: HwmcOnlyHeader.inc
//
// Header file used only in HWMC_ONLY mode
//

#include "header.inc"

#if !defined(__HWMCONLYHEADER__)	// Make sure the following are only included once
#define __HWMCONLYHEADER__

.reg_count_total    64
.reg_count_payload  2

//
//  Now, begin source code....
//

.code
#endif	// !defined(__HWMCONLYHEADER__)

