/*
 * All Video Processing kernels 
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */

// Modual name: undefall.inc
//
// undefine all global symbol for new process
//

//Source definitions
#undef  ubSRC_Y   
#undef  ubSRC_U   
#undef  ubSRC_V 

#undef  ub2SRC_Y   
#undef  ub2SRC_U   
#undef  ub2SRC_V

#undef  ub4SRC_Y   
#undef  ub4SRC_U   
#undef  ub4SRC_V

#undef  uwSRC_Y   
#undef  uwSRC_U   
#undef  uwSRC_V

#undef  udSRC_Y   
#undef  udSRC_U   
#undef  udSRC_V

#undef  udSRC_YUV
#undef  nSRC_YUV_REG

//Destination definitions
#undef  ubDEST_Y   
#undef  ubDEST_U   
#undef  ubDEST_V 

#undef  ub2DEST_Y   
#undef  ub2DEST_U   
#undef  ub2DEST_V

#undef  ub4DEST_Y   
#undef  ub4DEST_U   
#undef  ub4DEST_V

#undef  uwDEST_Y   
#undef  uwDEST_U   
#undef  uwDEST_V

#undef  udDEST_Y   
#undef  udDEST_U   
#undef  udDEST_V

#undef  udDEST_YUV
#undef  nDEST_YUV_REG
#undef  ubDEST_ARGB

// End of undefall.inc
