/*
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */
// Modual name: Child_Undefs.inc
//
// Undefine global symbols for new process in child thread
//

#undef		P1	
#undef		P2	
#undef		P3	
#undef		P4
#undef		P5
#undef		P6
#undef		P7
#undef		P8
#undef		EDGECNTLMAP
#undef		CLIP_NEGATIVE
#undef		CLIP_DONE
