/*
 * Copyright © <2010>, Intel Corporation.
 *
 * This program is licensed under the terms and conditions of the
 * Eclipse Public License (EPL), version 1.0.  The full text of the EPL is at
 * http://www.opensource.org/licenses/eclipse-1.0.php.
 *
 */
// Modual name: Root_Undefs.inc
//
// Undefine global symbols for new process in root thread
//

#undef 		READ_BI
#undef 		WRITE_BI

#undef		ILDB_H_INDEPENDENT
#undef		ILDB_H_INDEPENDENT_CONT
#undef		ILDB_H_DEPENDENT
#undef		ILDB_H_DEPENDENT_SCAN
#undef		ILDB_H_NO_DEPENDENT

#undef		ILDB_V_INDEPENDENT
#undef		ILDB_V_INDEPENDENT_CONT
#undef		ILDB_V_DEPENDENT
#undef		ILDB_V_DEPENDENT_SCAN
#undef		ILDB_V_NO_DEPENDENT
