name: freebsd

on:
  push:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/freebsd.yml'
  pull_request:
    paths-ignore:
    - '.github/workflows/**'
    - '!.github/workflows/freebsd.yml'

jobs:
  freebsd:
    runs-on: macos-12
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Install prerequisites and build'
      uses: vmactions/freebsd-vm@v0
      with:
        prepare: |
          pkg install -y meson pkgconf libdrm libXext libXfixes wayland
          pkg install -y -x '^mesa($|-libs)'
        run: |
          meson setup _build
          meson compile -C _build
          meson install -C _build
